### ISSUE TITLE
login with facebook error

### ISSUE THREAD

**Issue by Nishtha-Iwebservices** [instaflutter/flutter-login-screen-firebase-auth-facebook-login#18] opened 2021-10-18 15:10 UTC
when I tap on login with facebook, facebook dialog comes and suddenly dismiss and give error couldn't login with facebook.
Can you please let me know the error behind this?
I am getting the same in my project also.

**Comment by mostafaAbdelazim** [comment] 2021-10-19 07:23
Hi, which platform are you experiencing this behavior on? Android, ios or both?

**Comment by mostafaAbdelazim** [comment] 2021-11-01 12:36
Closing this as we can't reproduce the error, feel free to comment back with the reproduction steps and i'll reopen.

**Closed as completed by mostafaAbdelazim** 2021-11-01 12:36 UTC
